In [1]:
!pip install torch torchvision

In [3]:
import torch

tensor_a = torch.tensor([1.0,2.0,3.0])
print("Tensor A :",tensor_a)

tensor_b = torch.rand(2,3)
print("Tensor B :" , tensor_b)

tensor_c = torch.zeros(3,3)
print("Tensor C :" ,tensor_c)

Tensor A : tensor([1., 2., 3.])
Tensor B : tensor([[0.6341, 0.9472, 0.4075],
        [0.3925, 0.0010, 0.8013]])
Tensor C : tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [4]:
result_add = tensor_a + torch.tensor([4.0,5.0,6.0])
print("Addition Result :",result_add)

result_mul = tensor_a * torch.tensor([4.0,5.0,6.0])
print("Mulitplicaiton Result :",result_mul)

matrix_a = torch.rand(2,3)
matrix_b = torch.rand(3,2)
result_matmul = torch.mm(matrix_a,matrix_b)
print("matrix Multiplication :", result_matmul)

Addition Result : tensor([5., 7., 9.])
Mulitplicaiton Result : tensor([ 4., 10., 18.])
matrix Multiplication : tensor([[0.5516, 0.3855],
        [0.8388, 0.4589]])


In [6]:
x = torch.tensor(2.0,requires_grad=True)
y = x**2+3*x+5
y.backward()
print("Gradient of y w.r.t x:" ,x.grad)


Gradient of y w.r.t x: tensor(7.)


In [7]:
import torch
import torch.nn as nn
import torch.optim as optim

x_train = torch.tensor([[1.0],[2.0],[3.0]],requires_grad=True)
y_train = torch.tensor([[2.0],[4.0],[6.0]])

model = nn.Linear(1,1)

criterian = nn.MSELoss()
optimizer = optim.SGD(model.parameters(),lr=0.1)

for epoch in range(100):
    optimizer.zero_grad()
    y_pred = model(x_train)
    loss = criterian(y_pred,y_train)
    loss.backward()
    optimizer.step()
    if(epoch+1) %10 ==0:
        print(f"Epoch {epoch+1}:Loss{loss.item()}")


print("Weight",model.weight.item())
print("Bias",model.bias.item())

Epoch 10:Loss0.014528715051710606
Epoch 20:Loss0.008930441923439503
Epoch 30:Loss0.005489341448992491
Epoch 40:Loss0.0033741591032594442
Epoch 50:Loss0.0020740206819027662
Epoch 60:Loss0.0012748482404276729
Epoch 70:Loss0.0007836176082491875
Epoch 80:Loss0.00048167063505388796
Epoch 90:Loss0.00029607504257000983
Epoch 100:Loss0.00018198984616901726
Weight 1.9847084283828735
Bias 0.03476130962371826


In [11]:
import torch
import torch.nn as nn
import torch.optim as optim

from torchvision import datasets,transforms

transform = transforms.Compose([transforms.ToTensor()])
train_dataset = datasets.MNIST(root="./data",train=True,transform=transform,download=True)
train_loader = torch.utils.data.DataLoader(dataset=train_dataset,batch_size=64,shuffle=True)

class CNN(nn.Module):
    def __init__(self):
        super(CNN,self).__init__()
        self.conv1 = nn.Conv2d(1,16,kernel_size = 3 , stride=1,padding=1)
        self.conv2 = nn.Conv2d(16,32,kernel_size=3,stride=1,padding=1)
        self.fc1 = nn.Linear(32*7*7,128)
        self.fc2 = nn.Linear(128,10)


    def forward(self,x):
        x = torch.relu(self.conv1(x))
        x = torch.max_pool2d(x,2)
        x = torch.relu(self.conv2(x))
        x = torch.max_pool2d(x,2)
        x = x.view(x.size(0),-1)
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

model = CNN()

criterian = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(),lr=0.001)

for epoch in range(5):
    for images,labels in train_loader:
        optimizer.zero_grad()
        outputs=model(images)
        loss = criterian(outputs,labels)
        loss.backward()
        optimizer.step()

print(f"Epoch{epoch+1} : Loss = {loss.item()}")

Epoch5 : Loss = 0.006146701518446207


In [16]:
from torch.utils.data import Dataset,DataLoader

class CustomDataset(Dataset):
    def __init__(self,data,labels):
        self.data = data
        self.labels= labels

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx], self.labels[idx]


data = torch.rand(100,3)
labels = torch.randint(0,2,(100,))
dataset = CustomDataset(data,labels)
dataloader = DataLoader(dataset,batch_size=10,shuffle=True)

for batch_data,batch_labels in dataloader:
    print(batch_data,batch_labels)

tensor([[2.6304e-01, 9.2933e-01, 5.7555e-01],
        [9.0181e-01, 9.9501e-01, 3.6050e-01],
        [6.4654e-01, 8.7927e-01, 5.6408e-01],
        [7.7357e-01, 4.9455e-01, 7.1377e-01],
        [4.5311e-04, 6.8612e-02, 2.9335e-01],
        [4.9727e-01, 4.5067e-01, 2.8121e-01],
        [9.2998e-01, 4.3772e-01, 5.8974e-01],
        [9.0739e-01, 2.9614e-01, 2.9442e-01],
        [5.1927e-01, 3.8071e-01, 7.7754e-01],
        [5.8162e-01, 7.0502e-01, 7.3698e-01]]) tensor([1, 1, 1, 0, 0, 0, 1, 1, 1, 0])
tensor([[0.1128, 0.7768, 0.5810],
        [0.7627, 0.0153, 0.2460],
        [0.6195, 0.5648, 0.0717],
        [0.3314, 0.6789, 0.5405],
        [0.9148, 0.8841, 0.5688],
        [0.8294, 0.3391, 0.8677],
        [0.5304, 0.0468, 0.2199],
        [0.1896, 0.7716, 0.4280],
        [0.1797, 0.8558, 0.2884],
        [0.1511, 0.7047, 0.7313]]) tensor([0, 1, 1, 0, 1, 0, 1, 0, 0, 1])
tensor([[0.4130, 0.4300, 0.3068],
        [0.1462, 0.8133, 0.8180],
        [0.4190, 0.6487, 0.7438],
        [0.0282, 0

In [17]:
from torchvision import models
resnet = models.resnet18(pretrained=True)

for param in resnet.parameters():
    param.requires_grad=False


resnet.fc = nn.Linear(resnet.fc.in_features,10)

criterian = nn.CrossEntropyLoss()
optimizer = optim.Adam(resnet.fc.parameters(),lr=0.001)


/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100%|██████████| 44.7M/44.7M [00:00<00:00, 168MB/s]
